version: '3.8'
services:
  orchestrator:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn orchestrator.orchestrator:app --host 0.0.0.0 --port 8000
  api_agent:
    build: .
    ports:
      - "8001:8001"
    command: uvicorn data_ingestion.api_agent:app --host 0.0.0.0 --port 8001
  scraper_agent:
    build: .
    ports:
      - "8002:8002"
    command: uvicorn data_ingestion.scraper_agent:app --host 0.0.0.0 --port 8002
  retriever_agent:
    build: .
    ports:
      - "8003:8003"
    command: uvicorn agents.retriever_agent:app --host 0.0.0.0 --port 8003
  analytics_agent:
    build: .
    ports:
      - "8004:8004"
    command: uvicorn agents.analytics_agent:app --host 0.0.0.0 --port 8004
  language_agent:
    build: .
    ports:
      - "8005:8005"
    command: uvicorn agents.language_agent:app --host 0.0.0.0 --port 8005
  voice_agent:
    build: .
    ports:
      - "8006:8006"
    command: uvicorn agents.voice_agent:app --host 0.0.0.0 --port 8006
  streamlit:
    build: .
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app/app.py --server.port 8501